package com.omar.bankapi.dto;

import com.omar.bankapi.model.AccountType;
import jakarta.validation.constraints.*;
import lombok.Data;

@Data
public class CreateAccountDTO {

    @Null(message = "Account number is generated by the server")
    private String accountNumber;

    @NotNull(message = "Account type is required")
    private AccountType type;

    @NotNull(message = "User id is required")
    private Long userId;
}
