package com.omar.bankapi.dto;

import com.omar.bankapi.model.enums.AccountType;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Null;
import jakarta.validation.constraints.Positive;

public record CreateAccountDTO(
        @Null(message = "Account number is generated by the server")
        String accountNumber,

        @NotNull(message = "Account type is required")
        AccountType type,

        @NotNull(message = "User id is required")
        @Positive(message = "User id must be a positive number")
        Long userId
) {}
