ALTER TABLE users
    ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE users
    ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE users
    ADD COLUMN deleted_at TIMESTAMP NULL;

ALTER TABLE accounts
    ADD COLUMN closed_at TIMESTAMP NULL;
